[package]
name = "dnp3rs"
version = "0.1.0"
authors = ["Adam Crain <jadamcrain@automatak.com>"]
edition = "2018"

[dependencies]
tokio = { version = "^0.2.11", features = ["tcp", "sync", "io-util", "time", "rt-core", "rt-threaded", "macros"]}