[package]
name = "dnp3-bindings"
version = "0.1.0"
authors = ["Émile Grégoire <emile@automatak.com>"]
edition = "2018"

[dependencies]
dnp3-ffi = { path = "../dnp3-ffi" }
dnp3-schema = { path = "../dnp3-schema" }
oo-bindgen = { git = "https://git@github.com/grid-io/oo_bindgen.git" }
c-oo-bindgen = { git = "https://git@github.com/grid-io/oo_bindgen.git" }
dotnet-oo-bindgen = { git = "https://git@github.com/grid-io/oo_bindgen.git" }
java-oo-bindgen = { git = "https://git@github.com/grid-io/oo_bindgen.git" }
